/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_root_hitr181b_JNI_AudioSwitch */

#ifndef _Included_com_example_root_hitr181b_JNI_AudioSwitch
#define _Included_com_example_root_hitr181b_JNI_AudioSwitch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    GetStringFormatNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_GetStringFormatNative
  (JNIEnv *, jobject);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_AdvLed
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1AdvLed
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_AdvAir
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1AdvAir
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_AdvFan
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1AdvFan
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_AdvRegri
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1AdvRegri
  (JNIEnv *, jobject, jboolean);

  /*
   * Class:     com_example_root_hitr181b_JNI_AudioSwitch
   * Method:    JNI_Set_AdvBuzzer
   * Signature: (Z)I
   */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1AdvBuzzer
  (JNIEnv *, jobject, jboolean);


/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_InternalMic
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1InternalMic
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_earphoneMic
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1earphoneMic
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_handsetMic
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1handsetMic
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_earphonespeaker
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1earphonespeaker
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_handsetspeaker
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1handsetspeaker
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_frontspeaker
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1frontspeaker
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_SOC_NURSE_SW
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1SOC_1NURSE_1SW
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_AdvCosensor
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1AdvCosensor
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_InternalMic
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1InternalMic
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_earphoneMic
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1earphoneMic
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_handsetMic
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1handsetMic
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_earphonespeaker
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1earphonespeaker
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_handsetspeaker
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1handsetspeaker
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_frontspeaker
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1frontspeaker
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_SOC_NURSE_SW
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1SOC_1NURSE_1SW
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_speakerdetect
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1speakerdetect
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_Micdetect
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1Micdetect
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_SOC_HOOK1_DET
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1SOC_1HOOK1_1DET
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_SOC_HOOK2_DET
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1SOC_1HOOK2_1DET
  (JNIEnv *, jobject, jbooleanArray);

#ifdef __cplusplus
}
#endif
#endif
