/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_example_root_hitr181b_JNI_AudioSwitch.h>

#include <android/log.h>  /* 注意这里 */
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>


#define LOG_TAG "HIT-R181B"
#define LOGE(a) __android_log_write(ANDROID_LOG_DEBUG,LOG_TAG,a);

#define GPIO_Define "/sys/class/gpio"
#define internal_Mic 74
#define earphone_speaker 75
#define earphone_Mic 76
#define handset_speaker 77
#define handset_Mic 78
#define front_speaker 81
#define SOC_NURSE_SW  209

#define SOC_HOOK1_DET 169
#define SOC_HOOK2_DET 215
#define earphone_speaker_detect 79
#define earphone_Mic_detect 80

//jinin added
#define adv_air 104
#define adv_regri 105
#define adv_fan 2
#define adv_led 106
#define adv_co	4

char c_logMsg[128];
int  int_logMsg;
struct HIT_R181_GPIO {
   int  number;
   char* direction;
};

static struct HIT_R181_GPIO hit_r181_gpio[] = {
    {74,"out"},
    {75,"out"},
    {76,"out"},
    {77,"out"},
    {78,"out"},
    {79,"in"},
    {80,"in"},
    {81,"out"},
    {169,"in"},
    {209,"out"},
    {251,"in"},
    {0xFFFF,"none"},
    {0xFFFF,"none"},
    {0xFFFF,"none"},
    {0xFFFF,"none"},
};

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    GetStringFormatNative
 * Signature: ()Ljava/lang/String;
 */

 int GPIO_unexort(void){
  char buff[64];
  int fd = 0xFFFFFFFF;
  int  bytes;
  int int_loop=0;


  bytes = snprintf(buff, sizeof(buff),"/sys/class/gpio/unexport");

  int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"initial_GPIO:%s\n",buff);
  LOGE(c_logMsg);


    fd = open(buff,O_WRONLY);
   if(fd < 0){
     int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"file open error [%s]\n",buff);
     LOGE(c_logMsg);

      return 0xFFFFFFFF;
   }
    int_loop=0;
  while(1){
   if(0xFFFF == hit_r181_gpio[int_loop].number){
      break;
    }
    bytes = 0;
    bytes = snprintf(buff, sizeof(buff),"%d",hit_r181_gpio[int_loop].number);
    if(0 == bytes){
     int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"write error [%s]\n",buff);
      LOGE(c_logMsg);
     return 0xFFFFFFFF;
    }
    if(0 > write(fd,buff,bytes) ){
      int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"unexport gpio%s error \n",buff);
          LOGE(c_logMsg);
    }else{
     int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"unexport gpio%s\n",buff);
     LOGE(c_logMsg);
    }
    int_loop++;
   }
      if(0xFFFFFFFF != fd){
          close(fd);
       }

  return 0;
 }

 int GPIO_export(void){
  char buff[64];
  int fd = 0xFFFFFFFF;
  int  bytes;
  int int_loop=0;


  bytes = snprintf(buff, sizeof(buff),"/sys/class/gpio/export");

  int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"initial_GPIO:%s\n",buff);
  LOGE(c_logMsg);


    fd = open(buff,O_WRONLY);
   if(fd < 0){
     int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"file open error [%s]\n",buff);
     LOGE(c_logMsg);

      return 0xFFFFFFFF;
   }
    int_loop=0;
  while(1){
   if(0xFFFF == hit_r181_gpio[int_loop].number){
      break;
    }
    bytes = 0;
    bytes = snprintf(buff, sizeof(buff),"%d",hit_r181_gpio[int_loop].number);
    if(0 == bytes){
     int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"write error [%s]\n",buff);
      LOGE(c_logMsg);
     return 0xFFFFFFFF;
    }
    if(0 > write(fd,buff,bytes) ){
      int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"exort gpio%s error \n",buff);
          LOGE(c_logMsg);
    }else{
     int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"exort gpio%s\n",buff);
     LOGE(c_logMsg);
    }
    int_loop++;
   }
    close(fd);

     int_loop=0;
     while(1){
      if(0xFFFF == hit_r181_gpio[int_loop].number){
         break;
       }

          bytes = snprintf(buff, sizeof(buff),"/sys/class/gpio/gpio%d/direction",hit_r181_gpio[int_loop].number);

         int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"initial_GPIO:%s\n",buff);
         LOGE(c_logMsg);

           fd = open(buff,O_RDWR);
            if(fd < 0){
               int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"open error [%s]\n",buff);
               LOGE(c_logMsg);
                int_loop++;
               continue;
             }

            bytes = snprintf(buff, sizeof(buff),"%s",hit_r181_gpio[int_loop].direction);
            if(0 > write(fd,buff,bytes) ){
              int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"exort gpio%d[%s] error \n",hit_r181_gpio[int_loop].number,buff);
              LOGE(c_logMsg);
            }else{
               int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"exort gpio%d[%s] \n",hit_r181_gpio[int_loop].number,buff);
              LOGE(c_logMsg);
            }
             close(fd);

        int_loop++;
     }




  return 0;
 }

 int Set_GPIO(int name,jboolean active){

  char buff[64],buff_data[64];
  int fd = 0xFFFFFFFF;
  int  bytes;

    bytes = snprintf(buff, sizeof(buff),"/sys/class/gpio/gpio%d/value",name);

  //  int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"Set_GPIO:%s\n",buff);
  //  LOGE(c_logMsg);

    fd = open(buff,O_RDWR);
    if(fd < 0){
   //  int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"Set_GPIO open error [%s]\n",buff);
   //  LOGE(c_logMsg);

     return 0xFFFFFFFF;
    }

   bytes = 0;
    bytes = snprintf(buff_data, sizeof(buff_data),"%d",(int) active);
    if(0 == bytes){
   //  int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"Set_GPIO write error [%s]\n",buff);
   //   LOGE(c_logMsg);
     return 0xFFFFFFFF;
    }
    if(0 > write(fd,buff_data,bytes) ){
      //int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"Set_GPIO gpio%s error \n",buff);
      //    LOGE(c_logMsg);
          close(fd);
            return 0xFFFFFFFF;
    }else{
    // int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"Set_GPIO gpio%s[%d]\n",buff,(int)active);
    // LOGE(c_logMsg);
    }

      close(fd);




  return 0;
 }

 int Get_GPIO(int name,int *active){

  char buff[64],buff_data[64];
  int fd = 0xFFFFFFFF;
  int  bytes;

    bytes = snprintf(buff, sizeof(buff),"/sys/class/gpio/gpio%d/value",name);

   // int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"Get_GPIO:%s\n",buff);
   // LOGE(c_logMsg);

    fd = open(buff,O_RDWR);
    if(fd < 0){
    // int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"Get_GPIO open error [%s]\n",buff);
    // LOGE(c_logMsg);

     return 0xFFFFFFFF;
    }

    bytes = read(fd, &buff_data[0], sizeof(buff_data));
    if (bytes < 0) {
     //    int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"Get_GPIO gpio%s error \n",buff);
    //     LOGE(c_logMsg);
          close(fd);
          return 0xFFFFFFFF;
    }else{
      //  int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"Get_GPIO gpio%s[%c]\n",buff,buff_data[0]);
      //  LOGE(c_logMsg);
    }


     close(fd);
     *active = atoi(&buff_data[0]);


  return 0;
 }

JNIEXPORT jstring JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_GetStringFormatNative
  (JNIEnv * env, jobject obj){


    //GPIO_unexort();
    //  GPIO_export();

    int_logMsg = snprintf(c_logMsg, sizeof(c_logMsg),"AudioSwitch GetStringFormatNative\n");
     LOGE(c_logMsg);
	   return (*env) ->NewStringUTF(env,"Audio Switch");
 }

//jinxin added
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1AdvLed
  (JNIEnv * env, jobject obj, jboolean active){
	LOGE("set led");
	if(active == 1){
	    LOGE("value: 1");
	}else{
	    LOGE("value: 0");
	}
  	return Set_GPIO(adv_led,active);
}
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1AdvAir
  (JNIEnv * env, jobject obj, jboolean active){
    LOGE("set air");
    if(active == 1){
        LOGE("value: 1");
    }else{
        LOGE("value: 0");
    }
    return Set_GPIO(adv_air,active);
}
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1AdvFan
  (JNIEnv * env, jobject obj, jboolean active){
    LOGE("set fan");
    if(active == 1){
        LOGE("value: 1");
    }else{
        LOGE("value: 0");
    }
    return Set_GPIO(adv_fan,active);
}
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1AdvRegri
  (JNIEnv * env, jobject obj, jboolean active){
    LOGE("set regri");
    if(active == 1){
        LOGE("value: 1");
    }else{
        LOGE("value: 0");
    }
    return Set_GPIO(adv_regri,active);
}
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1AdvBuzzer
  (JNIEnv * env, jobject obj, jboolean active){
    LOGE("set buzzer");
    if(active == 1){
        LOGE("value: 1");
        system("echo 1000  > /sys/devices/platform/imx-i2c.2/i2c-2/2-0058/da9063-regulators/buzzer");
    }else{
        LOGE("value: 0");
    }
    return 0;
}
//jinxin added end

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_InternalMic
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1InternalMic
  (JNIEnv * env, jobject obj, jboolean active){
   //    LOGE("Set_InternalMic");
	    return Set_GPIO(internal_Mic,active);
	 }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_earphoneMic
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1earphoneMic
  (JNIEnv * env, jobject obj, jboolean active){
   //   LOGE("Set_earphoneMic");
	    return Set_GPIO(earphone_Mic,active);
	 }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_handsetMic
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1handsetMic
  (JNIEnv * env, jobject obj, jboolean active){
   //         LOGE("Set_handsetMic");
	    return Set_GPIO(handset_Mic,active);
	 }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_earphonespeaker
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1earphonespeaker
  (JNIEnv * env, jobject obj, jboolean active){
    //    LOGE("Set_earphonespeaker");
	    return Set_GPIO(earphone_speaker,active);
	 }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_handsetspeaker
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1handsetspeaker
  (JNIEnv * env, jobject obj, jboolean active){
   //      LOGE("Set_handsetspeaker");
	    return Set_GPIO(handset_speaker,active);
	 }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Set_frontspeaker
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1frontspeaker
  (JNIEnv * env, jobject obj, jboolean active){
    //   LOGE("Set_frontspeaker");
	    return Set_GPIO(front_speaker,(active?JNI_FALSE:JNI_TRUE));
	 }

JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Set_1SOC_1NURSE_1SW
  (JNIEnv * env, jobject obj, jboolean active){
    //   LOGE("Set_frontspeaker");
	    return Set_GPIO(SOC_NURSE_SW,active);
	 }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_AdvCosensor
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1AdvCosensor
  (JNIEnv * env, jobject obj, jbooleanArray active){
    	LOGE("Get_AdvCosensor");
        int i_active[1];
        int rc;
        rc= Get_GPIO(adv_co,i_active);
        if(i_active[0] == 0){
            LOGE("get value: 0");
        }else{
            LOGE("get value: 1");
        }
        jboolean* pjbIngnition = (*env)->GetBooleanArrayElements(env,active, NULL);

        if(i_active[0]){
        *pjbIngnition = JNI_TRUE;
        }else{

        *pjbIngnition = JNI_FALSE;
        }
        (*env)->ReleaseBooleanArrayElements(env,active, pjbIngnition, 0);

        return rc;
     }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_InternalMic
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1InternalMic
  (JNIEnv * env, jobject obj, jbooleanArray active){
    //    LOGE("Get_InternalMic");
        int i_active[1];
        int rc;
        rc= Get_GPIO(internal_Mic,i_active);

        jboolean* pjbIngnition = (*env)->GetBooleanArrayElements(env,active, NULL);

        if(i_active[0]){
        *pjbIngnition = JNI_TRUE;
        }else{

        *pjbIngnition = JNI_FALSE;
        }
        (*env)->ReleaseBooleanArrayElements(env,active, pjbIngnition, 0);

        return rc;
	 }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_earphoneMic
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1earphoneMic
  (JNIEnv * env, jobject obj, jbooleanArray active){
    //    LOGE("Get_earphoneMic");
        int i_active[1];
        int rc;
        rc= Get_GPIO(earphone_Mic,i_active);

        jboolean* pjbIngnition = (*env)->GetBooleanArrayElements(env,active, NULL);

        if(i_active[0]){
        *pjbIngnition = JNI_TRUE;
        }else{

        *pjbIngnition = JNI_FALSE;
        }
        (*env)->ReleaseBooleanArrayElements(env,active, pjbIngnition, 0);

        return rc;

	 }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_handsetMic
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1handsetMic
  (JNIEnv * env, jobject obj, jbooleanArray active){
    //    LOGE("Get_handsetMic");
        int i_active[1];
        int rc;
        rc= Get_GPIO(handset_Mic,i_active);

        jboolean* pjbIngnition = (*env)->GetBooleanArrayElements(env,active, NULL);

        if(i_active[0]){
        *pjbIngnition = JNI_TRUE;
        }else{

        *pjbIngnition = JNI_FALSE;
        }
        (*env)->ReleaseBooleanArrayElements(env,active, pjbIngnition, 0);

        return rc;
	 }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_earphonespeaker
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1earphonespeaker
  (JNIEnv * env, jobject obj, jbooleanArray active){
     //   LOGE("Get_earphonespeaker");
        int i_active[1];
        int rc;
        rc= Get_GPIO(earphone_speaker,i_active);

        jboolean* pjbIngnition = (*env)->GetBooleanArrayElements(env,active, NULL);

        if(i_active[0]){
        *pjbIngnition = JNI_TRUE;
        }else{

        *pjbIngnition = JNI_FALSE;
        }
        (*env)->ReleaseBooleanArrayElements(env,active, pjbIngnition, 0);

        return rc;
	 }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_handsetspeaker
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1handsetspeaker
  (JNIEnv * env, jobject obj, jbooleanArray active){
    //    LOGE("Get_handsetspeaker");
        int i_active[1];
        int rc;
        rc= Get_GPIO(handset_speaker,i_active);

        jboolean* pjbIngnition = (*env)->GetBooleanArrayElements(env,active, NULL);

        if(i_active[0]){
        *pjbIngnition = JNI_TRUE;
        }else{

        *pjbIngnition = JNI_FALSE;
        }
        (*env)->ReleaseBooleanArrayElements(env,active, pjbIngnition, 0);

        return rc;
	 }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_frontspeaker
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1frontspeaker
  (JNIEnv * env, jobject obj, jbooleanArray active){
        int i_active[1];
        int rc;
        rc= Get_GPIO(front_speaker,i_active);

        jboolean* pjbIngnition = (*env)->GetBooleanArrayElements(env,active, NULL);

        if(i_active[0]){
        *pjbIngnition = JNI_FALSE;
        }else{

        *pjbIngnition =  JNI_TRUE;
        }
        (*env)->ReleaseBooleanArrayElements(env,active, pjbIngnition, 0);

        return rc;
	 }

JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1SOC_1NURSE_1SW
 (JNIEnv * env, jobject obj, jbooleanArray active){
        int i_active[1];
        int rc;
        rc= Get_GPIO(SOC_NURSE_SW,i_active);

        jboolean* pjbIngnition = (*env)->GetBooleanArrayElements(env,active, NULL);

        if(i_active[0]){
        *pjbIngnition =  JNI_TRUE;
        }else{

        *pjbIngnition = JNI_FALSE ;
        }
        (*env)->ReleaseBooleanArrayElements(env,active, pjbIngnition, 0);

        return rc;
     }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_speakerdetect
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1speakerdetect
  (JNIEnv * env, jobject obj, jbooleanArray active){

    //    LOGE("Get_speakerdetect");
        int i_active[1];
        int rc;
        rc= Get_GPIO(earphone_speaker_detect,i_active);

        jboolean* pjbIngnition = (*env)->GetBooleanArrayElements(env,active, NULL);

        if(i_active[0]){
        *pjbIngnition = JNI_FALSE;

        }else{

        *pjbIngnition = JNI_TRUE ;
        }
        (*env)->ReleaseBooleanArrayElements(env,active, pjbIngnition, 0);

        return rc;

	 }

/*
 * Class:     com_example_root_hitr181b_JNI_AudioSwitch
 * Method:    JNI_Get_Micdetect
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1Micdetect
  (JNIEnv * env, jobject obj, jbooleanArray active){
     //   LOGE("Get_Micdetect");
        int i_active[1];
        int rc;
        rc= Get_GPIO(earphone_Mic_detect,i_active);

        jboolean* pjbIngnition = (*env)->GetBooleanArrayElements(env,active, NULL);

        if(i_active[0]){
        *pjbIngnition = JNI_FALSE;
        }else{

        *pjbIngnition = JNI_TRUE ;
        }
        (*env)->ReleaseBooleanArrayElements(env,active, pjbIngnition, 0);

        return rc;
	 }

JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1SOC_1HOOK1_1DET
(JNIEnv * env, jobject obj, jbooleanArray active){
     //   LOGE("Get_Micdetect");
        int i_active[1];
        int rc;
        rc= Get_GPIO(SOC_HOOK1_DET,i_active);

        jboolean* pjbIngnition = (*env)->GetBooleanArrayElements(env,active, NULL);

        if(i_active[0]){
        *pjbIngnition = JNI_FALSE;
        }else{

        *pjbIngnition = JNI_TRUE ;
        }
        (*env)->ReleaseBooleanArrayElements(env,active, pjbIngnition, 0);

        return rc;
	 }

JNIEXPORT jint JNICALL Java_com_example_root_hitr181b_JNI_1AudioSwitch_JNI_1Get_1SOC_1HOOK2_1DET
(JNIEnv * env, jobject obj, jbooleanArray active){
     //   LOGE("Get_Micdetect");
        int i_active[1];
        int rc;
        rc= Get_GPIO(SOC_HOOK2_DET,i_active);

        jboolean* pjbIngnition = (*env)->GetBooleanArrayElements(env,active, NULL);

        if(i_active[0]){
        *pjbIngnition = JNI_FALSE;
        }else{

        *pjbIngnition = JNI_TRUE ;
        }
        (*env)->ReleaseBooleanArrayElements(env,active, pjbIngnition, 0);

        return rc;
	 }
